### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by ray0809** [zjxeditor/FFTracker#1]
Hi friend,
    after compile your code in macOS, I just run the basic code `./run,` It does not work
    here is the print informations
    `dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/8/libgfortran.5.dylib
  Referenced from: /usr/local/opt/openblas/lib/libopenblasp-r0.3.5.dylib
  Reason: image not found
Abort trap: 6`
    Could you help me to solve the problem

**Comment by ray0809** [comment]
Hi friend,  
Now, I have fix this problem  
**Compile step**    

```
>mkdir Release  
 >cd Release & cmake .. & make -j8
```
**gcc@8**  
because the precompiled file in Thirdparty with gcc@8
```
>brew install gcc@8
 >mv /usr/local/opt/gcc@8 /usr/local/opt/gcc
 >brew install libusb
```

**Comment by zjxeditor** [comment]
Hope you have fun with this project.
